### PR TITLE
Feature/npr

### PR DESCRIPTION
**Pull request by felixerben**
29/11/2020: I recommend to merge this. This is Ryan's code, amended to obey the usual Hadrons design principles. Bilinear, FourQuarkFullyConnected, ExternalLeg are checked and tested to a high standard by Fabian, Max, Toby and are used in production (on CPU) in two projects already. In all regards, this code is superior to the one currently in develop.

Done so far:

- [x] superfluous modules removed
- [x] all modules derive their types from FImpl
- [x] common code externalised to header to avoid code duplication
- [x] Bilinear, FourQuarkFullyConnected, ExternalLeg are tested by Max&Fabian to be consistent with analytical solution on unit gauge 
- [x] Checked that the output is consistent with Ryan's original modules 
- [x] GPU build works

Still to do:
- [ ]  Warning in FourQuarkFullyConnected: Does not work with GPU, realted to Grid issue #372
- [ ] Warning in G1.hpp: Iwasaki gauge action enforced -> later pull request
- [ ] General work on FourQuarkLoop, G1, SubtractionOperators from our side has been minimal -> think about this in a future pull request.

### CODE REVIEW

**Comment by felixerben** [comment]
ready to merge

**Review by aportelli — CHANGES_REQUESTED** [review]
Please resolve conflicts with `develop`. There are re-indentation commits in unrelated part of the code. Please do not submit these changes.

**Comment by felixerben** [comment]
conflicts resolved, builds and runs locally without errors.

**Comment by aportelli** [comment]
@felixerben @fjosw Is that the version that takes 5 days to compile with nvcc 11?
If yes could somebopdy please give me a hand and makes the compilation of the problematic part optional, using a macro guard and ideally an additional `--enable-npr-whatever` option in `configure`?

**Comment by fjosw** [comment]
This is the most recent version with which we started production runs. The fourquark module causing the extremely long compile times on tursa is disabled by default and can be enabled via `--enable-npr-fourquark`. As soon as a solution for the gpu sum of large objects is available we might change this behavior. From @felixerben's and my perspective this PR is ready to be merged into develop.

**Comment by felixerben** [comment]
yes this is still up to date! The only changes since your last comment are the compilation flag which Fabian added.

**Comment by fjosw** [comment]
There will be a few minor changes related to the gpu sum adjustements in Grid (see https://github.com/felixerben/Hadrons/pull/27). I would propose to wait with the merge until these changes have made it into Grid.

**Comment by aportelli** [comment]
Noted, thanks!

**Comment by aportelli** [comment]
I changed the status to draft, please mark it ready for review when done, thanks!

**Comment by felixerben** [comment]
Thanks a lot Fabian for all the work! With the gpu_sum being in grid now, this is ready to be merged into Hadrons.

**Comment by aportelli** [comment]
Thanks all for the hard work on that, the code is really clean

**Pull request merged**
