### PR TITLE
Noise Refactor

### PR DESCRIPTION
**Pull request by fionnoh**
This (so far empty) pull request is in preparation for the following changes we want to make:

- [x] @fionnoh Change the container in DilutedNoise.hpp such that:
- the naming convention is a bit less cumbersome, all noises will be SpinColorDiagonal
- getNoise(void) is changed to return `LatticeComplex`, not `std::vector<FermionField>`
- getFerm(const unsigned int i) is added and returns `FermionField`
- getProp(const unsigned int i) is added and returns `PropagatorField`
- operator[] is removed
- [x] @fionnoh  Update the A2A and Distillation setups to reflect the above changes
- essentially changes all instances of `noise[i`] to `noise.getFerm(i)`
- [x] @aportelli Create a private function in GaugeProp module that performs what the current execute() function does so that it can be called for either a `std::vector<PropagatorField>` or a single `PropagatorField`
- [x] @aportelli Create a vector version of the sequential source modules
- [x] @fionnoh Create a Z2Sparse module that creates `std::vector<PropagatorField>`
- [x] @aportelli Create a (module? utility?) that unpacks a `std::vector<PropagatorField>` such that the propagators can be used individually in the contraction code.

### CODE REVIEW

**Comment by fionnoh** [comment]
@aportelli How this this look? I think you have permission to edit, so feel free to change anything that isn't clear/you disagree with (what we're doing with operator[] is a bit unclear to me, for instance).

**Comment by fionnoh** [comment]
Some notes on what I've added:

For DliutedNoise.hpp :

- getNoise(void) returns `std::vector<LatticeComplex>` because the full volume noise has multiple hits and there's no reason the others can't either.
- I made it such that the others noises can also have multiple hits, but left the interface of the modules the same for now (so the time diluted module still creates one hit by default, but if someone wants to change that in the future it should be trivial).
- I think there was a bug in the previous full volume noise implementation, [line 255:](https://github.com/aportelli/Hadrons/blob/develop/Hadrons/DilutedNoise.hpp#L255) this should be in the nSrc_ for loop, no? We should discuss this tomorrow of Tuesday.
- I have tested all the changes locally. When I used the pokeSpin, pokeColour implementation and saved the A2A vectors the results were exactly the same (diff'ing the files showed no difference). Using the PropToFerm implementation (as it is now) and printing the A2A vectors to file show that they are the same up to some plus/minus zeros. We should discuss if we want more rigorous testing tomorrow or Tuesday.

For A2A and distillation:

- A2A refactor was trivial
- We don't seem to need to do anything for distillation. As far as I can tell the IO from A2AVectors is used but despite the fact that the DilutedNoise.hpp header is included I don't think there's any actual dependence. I will make sure on the call tomorrow by discussing with Felix or Micheal if possible.

For Z2Sparse module

- I made a generic Z2Diluted module instead. This takes any of the noises.

Sparse Noise

- I renamed the old sparse noise to checkerboard and added the new sparse noise.

**Comment by aportelli** [comment]
Ok now that the CI is done I started working on my changes, branch `feature/vector-inputs`

**Comment by aportelli** [comment]
I have done the packing and the multiple source solver. I will do the sequential tomorrow.

**Comment by aportelli** [comment]
I tested the unpacking with

```xml
  <modules>
    <module>
      <id>
        <name>vec</name>
        <type>MUtilities::RandomFermions</type>
      </id>
      <options>
        <size>12</size>
        <Ls>1</Ls>
        <output/>
        <multiFile>false</multiFile>
      </options>
    </module>
    <module>
      <id>
        <name>vec_up</name>
        <type>MUtilities::FermionVectorUnpack</type>
      </id>
      <options>
        <input>vec</input>
      </options>
    </module>
  </modules>
```

**Comment by aportelli** [comment]
I added the vector version of the sequential modules. There is some duplication in the code that should probably be dealt with, but this is internal you should go ahead with the current status.
Merge fionnoh#1 to integrate my changes into this PR.

**Comment by fionnoh** [comment]
I added the loop propagator module to MContraction.

Also the vector unpack module did not have the individual vectors as an output so they could not be found in the environment. To do so we need the size of the vector but the vector's setup() won't have run before the unpack's getOutput(). So the vector neither has a size nor is in the environment to begin with. I added in a size parameter to the unpack module with an assert in setup() that check if this size and the vector size are equal.

The CNL CI test failed after the last merge but the error was very ambiguous. I'll keep an eye on it.

**Comment by aportelli** [comment]
Good catch about the size, I did not do a test where the vectors are an input to something else, saw them in the environment and overlooked that.
Yes the way Hadrons is build so far the graph of objects and modules cannot be dependent on specific runtime properties of objects. So I think the solution you used is the best we can do, however please use `HADRONS_ERROR` exceptions rather than an assert.

**Comment by aportelli** [comment]
The KNL CI is an issue with the machine, I was planing to look at it today.

**Comment by fionnoh** [comment]
Yes a `HADRONS_ERROR` exception is what it is at the moment.

I have set up the rare kaon production code, in doing so I have come across two more issues.

One was a minor Ls bug in the sequential source module.
The other was an issue with how I was treating the size() function in the `DilutedNoise` container. Before it was returning the `FermionField` size, which wasn't appropriate for creating an `std::vector<PropagatorField>`. I have instead created the functions size(), fermSize() and propSize() which return the `LatticeComplex`, `FermionField`, and `PropagatorField` sizes respectively. I updated the A2AVector module to reflect this change.

I think that's it. There's maybe a question of memory restraints, but we can talk about that on Tuseday before merging this pull request.

**Comment by aportelli** [comment]
Thanks, I'll try to review it all before Tuesday. The KNL builds are fine, it was just a silly disk space issue on the agent's SSD.

**Comment by fionnoh** [comment]
Ok, no more conflicts and all the tests pass. This should be it.

**Pull request merged**
