### PR TITLE
add A2ASmearedMesonField

### PR DESCRIPTION
**Pull request by nils-asmussen**
For further information please refer to *redacted*
Edit: no RBC-UKQCD internal link here

### CODE REVIEW

**Comment by nils-asmussen** [comment]
Update: For the zero momentum case I verified entry by entry with a completely independent program that I can reproduce the complete meson field generated from random A2A vectors with finite smearing radius.

**Comment by aportelli** [comment]
Is the situation with the Regensburg phase A2A vs traditional clarified?

**Comment by aportelli** [comment]
I am trying to clean PRs, at this stage it does not seem you are interested to solve and close that, in which case I am tempted to just close the PR. I am just trying to get sure this is the case, and if not could you propose a way forward please?

**Comment by nils-asmussen** [comment]
Hi Antonin,
Thank you for doing the housekeeping!
Concerning this pull request, I would say that the code is useful in the current status.
The A2ASmearedMesonField adds important smearing functionality to Hadrons, and is in my opinion worth merging.
I have rebased the request on the most recent develop code.

**Comment by nils-asmussen** [comment]
PS: I might have an update on the Regensburg phase next Monday. I am currently double checking...

**Comment by aportelli** [comment]
You know the issue, I don’t want to merge in a module which partially works. I am trying to have a high level of checks before code gets in, and there is no reasons I should make an exception here. Even by doing that we keep discovering issues here and there so I believe this is perfectly justified.

This functionality is a simple one, and was promised since 1.5 years ago which is really excessive. If I don’t hear from you by Monday, I will merge the code and move the A2A smeared module in the “Archive” module folder with other unused/broken modules to keep a copy of the code.

**Comment by nils-asmussen** [comment]
This module fully implements all features that are exposed by its interface, and it should work as is.
As I have presented on a Monday call some time ago, it reproduces the A2AMesonField results for a Kronecker delta as smearing function and it produces a meson with reduced excited states for a finite smearing radius, as expected.
The feature that is under discussion is the Regensburg phase only. It is therefore not part of this pull request.

Therefore I think this module should go into Hadrons in the usual location. I do NOT see a reason to put it in the Archive folder.

**Comment by nils-asmussen** [comment]
Thank you a lot, that is a compromise that works for me.
Apologies for the unfortunate communication on this topic, I hope we can find a good restart communication wise.
I will do the changes asap.

**Comment by nils-asmussen** [comment]
Hi Antonin,

I have removed the momentum feature and substituted LatticeFermion by FermionField and LatticeComplex by ComplexField.
With the help of the RandomVectors, I have checked that I still get the same meson fields with the modified code.
Let me know if the code looks okay to you or if you would like other changes to be made.

Best regards,
Nils

**Comment by nils-asmussen** [comment]
Thanks, the copyright should now be corrected.

**Comment by aportelli** [comment]
All good thanks

**Pull request merged**
