### PR TITLE
Four-quark NPR modules

### PR DESCRIPTION
**Pull request by rabbott99**
I've put together all of the substantial modules that I've created for 4-quark NPR. I've also included here a minor fix to the full-volume spin-color-diagonal noise generation bug I found -- I thought since the fix is so simple it doesn't make much sense leaving the bug in the main repository.

One potential issue here is the module "FourQuarkFullyConnected", which effectively replicates Julia Kettle's NPR module which is already present in Hadrons. This would create two modules with the same functionality and only minor differences; if desired I could remove the module to avoid this issue.

### CODE REVIEW

**Comment by aportelli** [comment]
Hi, thank you that's very useful. I'll come back with more feedback on the code. But first some file cleanup:
- [ ] If you think your module entirely replicates Julia's one, please remove the later. In any case it is saved in the git history.
- [ ] Regarding the conflicts, please update your `develop` branch. Some hints: 1) the modules file are automatically generated by `bootstrap.sh` now so just remove them 2) the refactor of the noise was merged so you can solve the conflict by systematically chasing the changes from `develop`.

**Comment by rabbott99** [comment]
I've removed the last module and fixed the merge conflicts. I could clean up the history a bit if needed but otherwise everything looks good on my end.

**Comment by aportelli** [comment]
Hi,

Sorry it took me so long to come back to you and thanks for the changes. There is one last potential issue which might need a bit of code refactoring. You used a lot hard-coded types like `LatticeSpinColourMatrix` which are completely independent from the `FImpl`. So it is likely that this code is not going to compile if one chooses `FImpl` to be something else than the default. The general way this is solved in Hadrons is to `typedef` the types you need from the `FImpl`, which is generally done by convenience macros like `FERM_TYPE_ALIASES`. This is how, for example, the `PropagatorField` is created.

I can see you have been using `PropagatorField` but that often `LatticeSpinColourMatrix` and `LatticeComplex` were used. Could you please changed that? If you do not have the types you want in `FERM_TYPE_ALIASES` do not hesitate to add them in `Global.hpp`.

Please let me know if I can help you in anyway, of if something above does not make sense.

**Comment by aportelli** [comment]
@mthansen @felixerben I am merging @rabbott99 code into the `feature/npr` branch. Please pull it and send new PRs for code update.

**Comment by aportelli** [comment]
Thank you @rabbott99 !!

**Pull request merged**
