### PR TITLE
Ward Identity module, courtesy of Andrew Lawson via Fionn O'Hogain

### PR DESCRIPTION
**Pull request by mmphys**
This is post-review and ready for inclusion in Hadrons.

### CODE REVIEW

**Review by aportelli — CHANGES_REQUESTED** [review]
Hi @mmphys it looks all good, just please review the types and make sure they all derive from the `FImpl` template parameters (e.g. `LatticeComplex`)

**Review by aportelli — CHANGES_REQUESTED** [review]
Hi, thanks! I see commits are still coming in, is it ready?
At least I spotted one things that I would like changed: don't append `_5d` to the propagator name (implicit behaviour specific to this module).

**Comment by mmphys** [comment]
> Hi, thanks! I see commits are still coming in, is it ready?
> At least I spotted one things that I would like changed: don't append `_5d` to the propagator name (implicit behaviour specific to this module).

Hi Antonin,

Yes, it looks as if this is ready and I wouldn’t expect any changes.

Anticipating that comment, one of the last changes I made was to make the caller specify the name of the 4d propagator and the 5d propagator in prop and prop5d parameters.

FYI, I am still bug hunting in the conserved currents in Grid.

Regards,

Michael

**Review by aportelli — CHANGES_REQUESTED** [review]
Hi Michael,

I am afraid I'll bother you with extra changes, although it looks all good. It is more physically related to the fact that part of the code does not make so much sense for other actions than DWF ones (however all actions have a conserved vector current). To answer your comment in the code, this is why the `test_axial` parameter was here, which is not super elegant either (I guess it came from Andrew L.).

I would suggest the following if that's fine with you:

- [ ] you do not need `prop` and `prop5d`, just have one `prop`, if the action is 5d this is expected to be the 5d one and in the code you can create the 4d one out of the action object.
- [ ] isolate all the axial/J5q business into a block, and make it conditional to 5d actions only, there are many ways to do that, but for the moment probably the easiest is to get the Ls property of the action object and test if it is larger than 1.

Let me know what you think.

**Comment by mmphys** [comment]
Hi Antonin, thanks for the review comments and explanation.
1) I've restored the axial test to being optional.
2) The 4d propagator is required, even for 5d actions, as it is used for the pseudoscalar density. So I've left this as is for now. Please take a look at lines 249 & 251 of WardIdentity.hpp, which sets up for the pseudoscalar density to be saved in line 258. Please grab me online when you are reviewing if that helps.

**Comment by aportelli** [comment]
Hi Michael, thanks
1. yes but we can avoid the boolean, one can look at the action Ls with `getObjectLs` and decide from there
2. if you know the 5d prop you know the 4d one too, so no need to input both. `ExportPhysicalFermionSolution` in the action class should compute the 4d one, the cost is negligible it sounds better to me than adding a parameter which is only relevant for a certain class of action

**Comment by mmphys** [comment]
Hi Antonin,

Thanks for the review feedback - I’ll get both of those changes done in the morning.

Re: 1 - apologies, I clearly didn’t read your comments properly!

Mike

**Comment by aportelli** [comment]
Actually for 2., `ExportPhysicalFermionSolution` is only available for fermion fields, not propagator. Still avoidable by looping it over spin and colour but maybe keeping the 5d & 4d input is ok then.

**Comment by mmphys** [comment]
Hi Antonin,

I’m very happy to do the loop over spin and colour.

I agree it would be much simpler to have a single propagator input, especially if the performance impact is negligible. This will probably save lots of broken runs, so I’m making this change now.

When I check it in, I will have tested on my laptop, but still need to check on Tesseract, so please wait for me to confirm before committing.

I’ll post again when I’m done.

Regards,

Michael

**Comment by aportelli** [comment]
Hi Michael, thanks, sounds great, I'll keep monitoring commits here t try closing that soon.

**Comment by mmphys** [comment]
Hi Antonin, I've finished testing on Tesseract that gpu and cpu results match, so if this passes your review, it's ready to merge into Hadrons. Please check that the loop around line 233 of WardIdentity.hpp is general enough before merging.

**Review by aportelli — APPROVED** [review]

**Comment by aportelli** [comment]
Ok thanks!

**Pull request merged**
